mysite/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [  
    path("polls/", include("polls.urls",)),
    path("polls/",include("django.contrib.auth.urls")),
     path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('',  include("polls.urls")),
]

polls/urls.py
from django.urls import include, path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/",include('django.contrib.auth.urls')),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path('<int:question_id>/<int:answer_id>/cancel_answer/', views.cancel_answer, name='cancel_answer'),
    path('<int:question_id>/end_answer/', views.end_answer, name='end_answer'),
    path('<int:question_id>/resume_question/', views.resume_question, name='resume_question')
]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model


from django.contrib import admin
  
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    creator = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, blank=True)
    is_finished = models.BooleanField(default=False)
    #is_paused = models.BooleanField(default=False)
    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def was_published_recently(self):
        now = timezone_now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def __str__(self):
        return self.question_text

    def save(self, *args, **kwargs):
        if not self.pk: 
            self.creator = get_user_model().objects.first()
        super().save(*args, **kwargs)

    def answers(self):
        return self.answer_set.all()

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

def was_published_recently(self):
    now = timezone.now()
    return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Answers(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, null=True)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    voter = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"{self.voter.username}'s answer to {self.question.question_text}"
    
    def save(self, *args, **kwargs):
        if not self.pk: 
            self.creator = get_user_model().objects.first()
        super().save(*args, **kwargs)



class Not_allowed(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, blank=True)
 
    def __str__(self):
        return self.request

class Persona(models.Model):
                nombre =  models.CharField(max_length=200)
                edad  =   models.IntegerField(default=0)
                
class Alumno(models.Model):
    nombres=models.CharField(max_length=255)
    apellido_paterno=models.CharField(max_length=255)
    apellido_materno=models.CharField(max_length=255)
    fecha_nacimiento= models.DateField("Born date")
    grado=models.CharField(max_length=255)
    grupo=models.CharField(max_length=10)

polls/views.py
"""
Vista para resolver peticiones de Polls
"""
from django.db.models import F
from django.views import generic
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render,redirect
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Choice, Question,Answers,Not_allowed


def index(request):
    return HttpResponse("Hola Mundo")




class DetailView(LoginRequiredMixin, generic.DetailView):
    model = Question
    template_name = "polls/detail.html"

    # def dispatch(self, request, *args, **kwargs):
    #     response = super().dispatch(request, *args, **kwargs)
    #     if request.user.answers_set.filter(question_id=kwargs.get("pk")):
    #         raise Http404
    #     return response

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data.update({
            "is_anwered": self.request.user.answers_set.filter(
                question=context_data["question"]
            ).exists()
        })
        # print(self.request.user.answers_set.filter(
        #     question=context_data["question"]
        # ).exists())
        print(context_data)
        return context_data
    


def detail(request, question_id):
    model = Answers
    question = get_object_or_404(Question, pk=question_id)
    
    # Get all answers for the current question
    answers = Answers.objects.filter(question=question).select_related('user')
    
    return render(request, 'polls/detail.html', {'question': question, 'answers': answers})

def cancel_answer(request,  answer_id,question_id,):
    question = get_object_or_404(Question, pk=question_id)
    answer = get_object_or_404(Answers, id=answer_id)
    
    if request.method == 'POST':
        if request.user == answer.voter:
            choice = get_object_or_404(Choice, pk=answer.choice_id)
            
           
            choice.votes -= 1
            
           
            choice.save()
            
            
            answer.delete()
        
        return HttpResponseRedirect(reverse("polls:detail", args=(question.id,)))
    
   
    return render(request, 'polls/detail.html', {'question': question})



def end_answer(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    
    if request.method == 'POST':
        question.is_finished = True
        question.save()
    
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))
    
    return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

def resume_question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    
    if request.method == 'POST':
        question.is_finished = False
        question.save()
    
        return HttpResponseRedirect(reverse("polls:detail", args=(question.id,)))
    
    return HttpResponseRedirect(reverse("polls:detail", args=(question.id,)))
   

class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    user = request.user

    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        Answers.objects.create(
            question=question,
            choice=selected_choice,
            voter=user
        )
        

        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))
    

polls/templates/polls/detail.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Pagina de detalless</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="styles.css">
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    <script src="script.js"></script>
  </head>
  <body><div class="centro">
    <h1>Detalle pregunta!</h1>

    
  {% if user.is_authenticated and not question.is_finished %}
    {% with answers=user.answers_set.all %}
      {% if is_anwered %}
      <legend><h2>{{ question.question_text }}</h2></legend>
      <h3 style="color: white;">UPPS Ya contestaste esta pregunta</h3>
      
        {% else %}
        <p >No haz Respondido esta Pregunta.</p>
        <form action="{% url 'polls:vote' question.id %}" method="post">
          {% csrf_token %}
          <fieldset>
              <legend><h2>{{ question.question_text }}</h2></legend>
              {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
              {% for choice in question.choice_set.all %}
                  <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                  <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
              {% endfor %}
          </fieldset>
          <input type="submit" value="Vote" class="button4">
          </form>
      {% endif %}
    {% endwith %}
    {% with answers=question.answers_set.all %}
    {% if answers %}
      <h2>Respuestas:</h2>
      <ul >
        {% for answer in answers %}
          <li style="color: black;">
            {{ answer.voter.username }} Respondio:
            {{ answer.choice.choice_text }}
            {% if request.user == answer.voter %}
              <form action="{% url 'polls:cancel_answer' question.id  answer.id %}" method="post">
                {% csrf_token %}
                <input type="submit" value="Cancelar respuesta" class="btn btn-danger">
              </form>
            {% endif %}
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p>Sin Respuestas.</p>
    {% endif %}
{% endwith %}

  
  {% if question.creator.id == user.id and question.is_finished == False %}

  <form action="{% url 'polls:end_answer' question.id %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Finalizar Pregunta" class="btn btn-danger">
  </form>

 
{% endif %}
{% else %}
<h2>Pregunta Finalizaada</h2>
<a href="{% url 'polls:results' question.id %}">Ver Resultados</a> </ul>


{% endif %}
{% if question.creator.id == user.id and question.is_finished == True %}

  <form action="{% url 'polls:resume_question' question.id %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Reaundar Pregunta" class="btn btn-danger">
  </form>
{% endif %}
 

  <button onclick="location.href='/polls'" class="button">Inicio</button>
  <a href="{% url 'polls:results' question.id %}">Ver Resultados</a> </ul>

</div>
  </body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html>

<head>
    <title>template</title>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

   
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="">
                <img src="" alt="logo" width="52" height="52"
                style="margin-right: 10px;">Test One
            </a>
            
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="">Check in</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="">Requests</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="">incidents</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " href="">Calendar</a>
                    </li>
                    <li class="nav-item">
                            <button type="submit" class="btn btn-success">
                              Contacto
                          </button>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
<div Class="Container">Contenido</div>

</body>
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</html>

polls/templates/polls/results.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>My Web Page Result</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="styles.css">
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    <script src="script.js"></script>
  </head>
  <body>
    <h1>Tutorial  Resultados Django!</h1>
    <h1 >{{ question.question_text }}</h1>

    <ul style="color: black;">
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>
    {% if question.creator.id == user.id and question.is_finished == True%}

    <form action="{% url 'polls:resume_question' question.id %}" method="post">
      {% csrf_token %}
      <input type="submit" value="Reaundar Pregunta" class="btn btn-danger">
    </form>
{% endif %}
  {% if question.creator.id == user.id and question.is_finished == False %}
  <form action="{% url 'polls:end_answer' question.id %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Finalizar Pregunta" class="btn btn-danger">
  </form>
  {% endif %}


    <a href="{% url 'polls:detail' question.id %}"  style="color: aliceblue;">Vota otra vez?</a>
    <button onclick="location.href='/polls'" class="button">Inicio</button>

  </body>
</html>